(function(){"use strict";var M=window.MERIDIAN;var reduce=window.matchMedia("(prefers-reduced-motion: reduce)").matches;var SAVE="meridian.saved",CMP="meridian.compare",THEME="meridian.theme";function read(k,f){try{return JSON.parse(localStorage.getItem(k))||f;}catch(e){return f;}}
function write(k,v){try{localStorage.setItem(k,JSON.stringify(v));}catch(e){}}
function applyTheme(t){document.documentElement.setAttribute("data-theme",t);try{localStorage.setItem(THEME,t);}catch(e){}}
function initTheme(){var saved;try{saved=localStorage.getItem(THEME);}catch(e){}
if(saved)applyTheme(saved);document.addEventListener("click",function(e){var t=e.target.closest("[data-theme-toggle]");if(!t)return;var cur=document.documentElement.getAttribute("data-theme")||"dark";applyTheme(cur==="dark"?"light":"dark");});}
var Saved={all:function(){return read(SAVE,[]);},has:function(id){return Saved.all().indexOf(id)>-1;},toggle:function(id){var s=Saved.all(),i=s.indexOf(id);if(i>-1)s.splice(i,1);else s.push(id);write(SAVE,s);sync();return i===-1;}};var Compare={all:function(){return read(CMP,[]);},has:function(id){return Compare.all().indexOf(id)>-1;},toggle:function(id){var s=Compare.all(),i=s.indexOf(id);if(i>-1)s.splice(i,1);else{if(s.length>=3){toast("Compare holds three at a time. Remove one first.");return false;}s.push(id);}
write(CMP,s);sync();return i===-1;},clear:function(){write(CMP,[]);sync();}};window.MERIDIAN_SAVED=Saved;window.MERIDIAN_COMPARE=Compare;function mount(){if(document.getElementById("mShared"))return;var w=document.createElement("div");w.id="mShared";w.innerHTML='<div class="scrim" data-close-all></div>'+
drawer("savedDrawer","Saved vehicles","savedBody","savedFoot")+
drawer("searchDrawer","Search inventory","searchBody",null,"left")+
compareBar()+'<div class="toast-region" id="toastRegion" role="status" aria-live="polite"></div>';document.body.appendChild(w);renderSearchDrawer();}
function drawer(id,title,bodyId,footId,side){return'<aside class="drawer'+(side==="left"?" drawer--left":"")+'" id="'+id+'" role="dialog" aria-modal="true" aria-label="'+title+'" aria-hidden="true">'+'<div class="drawer__head"><h2 class="h4">'+title+'</h2>'+'<button class="iconbtn" type="button" data-close-all aria-label="Close">'+xIcon()+'</button></div>'+'<div class="drawer__body" id="'+bodyId+'"></div>'+
(footId?'<div class="drawer__foot" id="'+footId+'"></div>':"")+'</aside>';}
function compareBar(){return'<div class="cmp-bar" id="cmpBar" aria-live="polite"></div>';}
function xIcon(){return'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round"><path d="M18 6 6 18M6 6l12 12"/></svg>';}
function toast(msg,link){var region=document.getElementById("toastRegion");if(!region)return;var t=document.createElement("div");t.className="toast";t.innerHTML='<svg class="ok" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m4 12.5 5 5L20 6.5"/></svg><span>'+M.esc(msg)+"</span>"+(link?' <a href="'+link+'">View</a>':"");region.appendChild(t);var timer,remaining=4000,started;function go(){started=Date.now();timer=setTimeout(close,remaining);}
function pause(){clearTimeout(timer);remaining-=Date.now()-started;}
function close(){t.classList.add("is-out");setTimeout(function(){t.remove();},350);}
t.addEventListener("mouseenter",pause);t.addEventListener("mouseleave",go);t.addEventListener("focusin",pause);t.addEventListener("focusout",go);go();}
window.MERIDIAN_TOAST=toast;var lastFocus=null;function open(el){lastFocus=document.activeElement;document.querySelector(".scrim").classList.add("is-open");el.classList.add("is-open");el.setAttribute("aria-hidden","false");document.body.style.overflow="hidden";var f=el.querySelector("input, button, a");if(f)setTimeout(function(){f.focus();},120);}
function closeAll(){var s=document.querySelector(".scrim");if(s)s.classList.remove("is-open");[].forEach.call(document.querySelectorAll(".drawer, .modal"),function(d){d.classList.remove("is-open");d.setAttribute("aria-hidden","true");});document.body.style.overflow="";if(lastFocus&&lastFocus.focus)lastFocus.focus();}
window.MERIDIAN_CLOSE=closeAll;function renderSavedDrawer(){var body=document.getElementById("savedBody"),foot=document.getElementById("savedFoot");if(!body)return;var ids=Saved.all();if(!ids.length){body.innerHTML='<div class="empty" style="border:0;padding:var(--s8) 0">'+'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="M20.8 5.6a5.5 5.5 0 0 0-7.8 0L12 6.6l-1-1a5.5 5.5 0 1 0-7.8 7.8l1 1L12 22l7.8-7.6 1-1a5.5 5.5 0 0 0 0-7.8z"/></svg>'+'<h3 class="h4">No saved vehicles yet</h3><p>Tap the heart on any vehicle to keep it here for later.</p>'+'<a class="btn btn--line" href="inventory.html">Browse inventory</a></div>';foot.innerHTML="";return;}
body.innerHTML=ids.map(function(id){var v=M.byId(id);if(!v)return"";return'<div style="display:flex;gap:14px;padding-bottom:16px;margin-bottom:16px;border-bottom:1px solid var(--line)">'+'<a href="vehicle.html?id='+v.id+'" class="plate" style="width:104px;flex:none;border-radius:10px;overflow:hidden;aspect-ratio:16/10">'+M.scene(v,{decorative:true})+'</a>'+'<div style="flex:1;min-width:0"><p class="vcard__marque">'+M.esc(v.marque)+'</p>'+'<p style="font-family:var(--f-display);font-weight:600;font-size:1.02rem;margin:2px 0 4px">'+M.esc(v.name)+'</p>'+'<p class="num" style="font-weight:800">'+M.eur(v.price)+'</p>'+'<button class="link-arrow" style="margin-top:8px;font-size:.68rem" data-save="'+v.id+'">Remove</button></div></div>';}).join("");foot.innerHTML='<a class="btn btn--gold btn--wide" href="inventory.html">Continue browsing</a>';}
function renderSearchDrawer(){var body=document.getElementById("searchBody");if(!body)return;body.innerHTML='<label class="vh" for="mSearchInput">Search inventory</label>'+'<input class="input" id="mSearchInput" type="search" placeholder="Marque, model, body or fuel…" autocomplete="off" style="height:56px;font-size:1.05rem">'+'<div style="display:flex;gap:8px;flex-wrap:wrap;margin:16px 0" id="mSearchQuick"></div>'+'<div id="mSearchResults" role="region" aria-live="polite"></div>';document.getElementById("mSearchQuick").innerHTML=["Electric","SUV","Coupe","Ferrari","Under €150k"].map(function(q){return'<button class="chip chip--gold" type="button" data-sq="'+q+'">'+q+'</button>';}).join("");runSearch("");}
function runSearch(q){var box=document.getElementById("mSearchResults");if(!box)return;q=q.trim().toLowerCase();var hits=M.VEHICLES;if(q){hits=M.VEHICLES.filter(function(v){if(q==="under €150k"||q==="under 150k")return v.price<150000;return(v.marque+" "+v.name+" "+v.body+" "+v.fuel+" "+v.city).toLowerCase().indexOf(q)>-1;});}else{hits=M.VEHICLES.slice(0,5);}
if(!hits.length){box.innerHTML='<p class="muted" style="padding:var(--s5) 0">Nothing matches “'+M.esc(q)+'”. Try a marque like <em>Porsche</em>, a body like <em>SUV</em>, or a fuel like <em>Electric</em>.</p>';return;}
box.innerHTML='<p class="faint num" style="font-size:.72rem;letter-spacing:.12em;text-transform:uppercase;margin-bottom:12px">'+hits.length+' result'+(hits.length>1?"s":"")+'</p>'+
hits.map(function(v){return'<a href="vehicle.html?id='+v.id+'" style="display:flex;gap:13px;align-items:center;padding:10px;border-radius:12px" onmouseover="this.style.background=\'var(--surface-2)\'" onmouseout="this.style.background=\'\'">'+'<span class="plate" style="width:78px;flex:none;border-radius:8px;overflow:hidden;aspect-ratio:16/10">'+M.scene(v,{decorative:true})+'</span>'+'<span style="min-width:0"><span class="vcard__marque">'+M.esc(v.marque)+'</span>'+'<span style="display:block;font-family:var(--f-display);font-weight:600;margin:2px 0 3px">'+M.esc(v.name)+'</span>'+'<span class="num" style="font-weight:800;font-size:.86rem">'+M.eur(v.price)+'</span></span></a>';}).join("");}
function renderCompareBar(){var bar=document.getElementById("cmpBar");if(!bar)return;var ids=Compare.all();if(!ids.length){bar.classList.remove("is-open");bar.innerHTML="";return;}
bar.classList.add("is-open");bar.innerHTML='<div class="cmp-bar__in">'+'<div class="cmp-bar__slots">'+
ids.map(function(id){var v=M.byId(id);return'<div class="cmp-bar__slot"><span class="plate">'+M.scene(v,{decorative:true})+'</span>'+'<span class="cmp-bar__name">'+M.esc(v.name)+'</span>'+'<button type="button" data-compare="'+id+'" aria-label="Remove '+M.esc(v.name)+'">'+xIcon()+'</button></div>';}).join("")+
Array(Math.max(0,3-ids.length)).fill('<div class="cmp-bar__slot cmp-bar__slot--empty">Add a vehicle</div>').join("")+'</div>'+'<div class="cmp-bar__act">'+'<button class="btn btn--ghost btn--sm" type="button" data-cmp-clear>Clear</button>'+'<a class="btn btn--gold btn--sm'+(ids.length<2?" ":"")+'" href="compare.html"'+(ids.length<2?' aria-disabled="true"':'')+'>Compare '+ids.length+'</a>'+'</div>'+'</div>';}
function initNav(){var nav=document.querySelector(".nav");if(!nav)return;function onScroll(){nav.classList.toggle("is-stuck",window.scrollY>30);}
onScroll();window.addEventListener("scroll",onScroll,{passive:true});var menu=nav.querySelector(".nav__menu");if(menu)menu.addEventListener("click",function(){var open=nav.classList.toggle("is-menu-open");menu.setAttribute("aria-expanded",String(open));});}
function initCounters(){var els=[].slice.call(document.querySelectorAll("[data-count]"));if(!els.length)return;function run(el){var target=parseFloat(el.dataset.count);var dec=(el.dataset.count.split(".")[1]||"").length;var suffix=el.dataset.suffix||"",prefix=el.dataset.prefix||"";if(reduce){el.textContent=prefix+target.toLocaleString("en-GB")+suffix;return;}
var start=performance.now(),dur=1600;function tick(now){var p=Math.min(1,(now-start)/dur);var e=1-Math.pow(1-p,3);var val=target*e;el.textContent=prefix+(dec?val.toFixed(dec):Math.round(val).toLocaleString("en-GB"))+suffix;if(p<1)requestAnimationFrame(tick);}
requestAnimationFrame(tick);}
var io=new IntersectionObserver(function(ents,obs){ents.forEach(function(en){if(en.isIntersecting){run(en.target);obs.unobserve(en.target);}});},{threshold:.5});els.forEach(function(el){io.observe(el);});}
function initReveal(){var els=[].slice.call(document.querySelectorAll(".reveal, .ribbon__cell"));if(!els.length)return;if(reduce||!("IntersectionObserver"in window)){els.forEach(function(el){el.classList.add("is-in");});return;}
var io=new IntersectionObserver(function(ents,obs){var n=0;ents.forEach(function(en){if(!en.isIntersecting)return;var el=en.target;setTimeout(function(){el.classList.add("is-in");},(n++)*70);obs.unobserve(el);});},{threshold:.12,rootMargin:"0px 0px -6% 0px"});els.forEach(function(el){var r=el.getBoundingClientRect();if(r.top<innerHeight&&r.bottom>0)el.classList.add("is-in");else io.observe(el);});setTimeout(function(){els.forEach(function(el){el.classList.add("is-in");});},2600);}
function sync(){var sc=Saved.all().length,cc=Compare.all().length;[].forEach.call(document.querySelectorAll("[data-saved-count]"),function(el){el.textContent=sc;el.hidden=sc===0;});[].forEach.call(document.querySelectorAll("[data-save]"),function(b){if(b.hasAttribute("aria-pressed"))b.setAttribute("aria-pressed",String(Saved.has(Number.isNaN(+b.dataset.save)?b.dataset.save:b.dataset.save)));});[].forEach.call(document.querySelectorAll("[data-save]"),function(b){if(b.hasAttribute("aria-pressed"))b.setAttribute("aria-pressed",String(Saved.has(b.dataset.save)));});[].forEach.call(document.querySelectorAll("[data-compare]"),function(c){if(c.type==="checkbox")c.checked=Compare.has(c.dataset.compare);});renderSavedDrawer();renderCompareBar();if(window.MERIDIAN_ON_SYNC)window.MERIDIAN_ON_SYNC();}
window.MERIDIAN_SYNC=sync;function init(){initTheme();mount();initNav();initReveal();initCounters();sync();document.addEventListener("click",function(e){var t=e.target;if(!t.closest)return;if(t.closest("[data-close-all]")){closeAll();return;}
if(t.closest("[data-open-saved]")){e.preventDefault();open(document.getElementById("savedDrawer"));return;}
if(t.closest("[data-open-search]")){e.preventDefault();open(document.getElementById("searchDrawer"));var i=document.getElementById("mSearchInput");if(i)setTimeout(function(){i.focus();},200);return;}
var save=t.closest("[data-save]");if(save){e.preventDefault();var on=Saved.toggle(save.dataset.save);if(save.classList.contains("vcard__save"))save.setAttribute("aria-pressed",String(on));toast(on?"Saved to your list.":"Removed from your list.");return;}
var cmp=t.closest("[data-compare]");if(cmp&&cmp.tagName==="BUTTON"){Compare.toggle(cmp.dataset.compare);return;}
if(t.closest("[data-cmp-clear]")){Compare.clear();return;}
var sq=t.closest("[data-sq]");if(sq){var inp=document.getElementById("mSearchInput");inp.value=sq.dataset.sq;runSearch(sq.dataset.sq);inp.focus();return;}});document.addEventListener("change",function(e){var cmp=e.target.closest("[data-compare]");if(cmp&&cmp.type==="checkbox"){var ok=Compare.toggle(cmp.dataset.compare);if(ok===false&&cmp.checked)cmp.checked=false;}});document.addEventListener("input",function(e){if(e.target.id==="mSearchInput")runSearch(e.target.value);});document.addEventListener("keydown",function(e){if(e.key==="Escape")closeAll();});document.addEventListener("click",function(e){var b=e.target.closest(".acc__btn");if(!b)return;var open=b.getAttribute("aria-expanded")==="true";b.setAttribute("aria-expanded",String(!open));var p=document.getElementById(b.getAttribute("aria-controls"));if(p)p.hidden=open;});}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();})();